name: 补充曲目
description: 推荐一首代表曲目
title: '[曲目] '
labels: [投稿, 曲目]
body:
  - type: input
    id: title
    attributes: { label: 歌名和艺人 }
    validations: { required: true }
  - type: input
    id: video
    attributes: { label: 视频链接, description: 优先官方上传 }
    validations: { required: true }
  - type: input
    id: year
    attributes: { label: 发行年份 }
  - type: textarea
    id: note
    attributes: { label: 推荐理由 }
  - type: textarea
    id: sources
    attributes: { label: 来源链接 }
