import os
import librosa, numpy as np, json, base64
A=os.environ.get('MV_AUDIO', 'audio/')
sr=22050; hop=256  # ~86 fps analysis
FPS=60
st={}
for k in ['vocals','drums','bass','other']:
    st[k],_=librosa.load(A+f'sep4/htdemucs/song22/{k}.wav',sr=sr,mono=True)
mix,_=librosa.load(A+'song22.wav',sr=sr)
dur=len(mix)/sr
f=librosa.fft_frequencies(sr=sr,n_fft=2048)
def band(y,lo,hi):
    S=np.abs(librosa.stft(y,n_fft=2048,hop_length=hop)); return np.sqrt((S[(f>=lo)&(f<hi)]**2).mean(0))
def rms(y): return librosa.feature.rms(y=y,frame_length=2048,hop_length=hop)[0]
ch={
 'voc': rms(st['vocals']),
 'kick': band(st['drums'],20,150),
 'snare': band(st['drums'],1500,8000),
 'bass': rms(st['bass']),
 'gtr': band(st['other'],150,1500),
 'vln': band(st['other'],1500,8000),
 'mix': rms(mix),
 'air': band(mix,6000,11000),
}
t_an=librosa.frames_to_time(np.arange(len(ch['mix'])),sr=sr,hop_length=hop)
N=int(np.ceil(dur*FPS)); tq=np.arange(N)/FPS
def ar(x,att,rel,fs):
    a=np.exp(-1/(att*fs)); r=np.exp(-1/(rel*fs)); y=np.zeros_like(x); p=0
    for i,v in enumerate(x):
        c=a if v>p else r; p=c*p+(1-c)*v; y[i]=p
    return y
out={}
for k,x in ch.items():
    x=np.interp(tq,t_an,x)
    ref=np.percentile(x,99.3) or 1
    x=np.clip(x/ref,0,1.2)
    x=np.sqrt(x)  # perceptual compress
    x=ar(x,0.012,0.16,FPS)
    x=np.clip(x/1.05,0,1)
    out[k]=x
# onsets
def onsets(y,lo=None,hi=None,delta=0.25,wait=6):
    S=np.abs(librosa.stft(y,n_fft=2048,hop_length=hop))
    if lo is not None: S=S[(f>=lo)&(f<hi)]
    env=librosa.onset.onset_strength(S=librosa.amplitude_to_db(S,ref=np.max),sr=sr,hop_length=hop)
    on=librosa.onset.onset_detect(onset_envelope=env,sr=sr,hop_length=hop,units='time',delta=delta,wait=wait,backtrack=False)
    st_=env[librosa.time_to_frames(on,sr=sr,hop_length=hop)]
    return on, st_/ (st_.max() or 1)
evs={}
for name,(y,lo,hi,dl) in {'kick':(st['drums'],20,150,0.35),'snare':(st['drums'],1500,8000,0.35),'bass':(st['bass'],None,None,0.3),'vln':(st['other'],1500,8000,0.3),'gtr':(st['other'],150,1500,0.3)}.items():
    on,s=onsets(y,lo,hi,dl)
    # gate by energy of that channel
    keep=[(round(float(t),3),round(float(v),2)) for t,v in zip(on,s) if out[name][min(N-1,int(t*FPS)+2)]>0.18]
    evs[name]=keep; print(name,len(keep))
tempo,beats=librosa.beat.beat_track(onset_envelope=librosa.onset.onset_strength(y=mix,sr=sr,hop_length=hop),sr=sr,hop_length=hop,units='time')
beats=[round(float(b),3) for b in beats]
# pack 8 channels uint8
keys=list(out.keys())
arr=np.stack([np.round(out[k]*255).astype(np.uint8) for k in keys],1)  # N x C interleaved
b64=base64.b64encode(arr.tobytes()).decode()
lyr=json.load(open('lyrics_timed.json'))
data={'dur':round(dur,3),'fps':FPS,'keys':keys,'n':int(N),'env':b64,'beats':beats,'downbeatOffset':1,'bpm':round(float(np.atleast_1d(tempo)[0]),3),'events':evs,
 'sections':[['intro',0,22.9],['v1',22.9,39.6],['pc1',39.6,57.2],['c1',57.2,79.5],['v2',79.5,97.3],['pc2',97.3,113.4],['c2',113.4,132.8],['br',132.8,153.5],['inst',153.5,161.1],['fc',161.1,204],['out',204,dur]],
 'bassGone':130.4,'bassBack':180.74,
 'lyrics':[{'t0':l['t0'],'t1':l['t1'],'text':l['text'],'c':[[c,t] for c,t in l['chars']]} for l in lyr]}
s='/* generated by tools/export_audio.py — audio analysis of the song (stems via Demucs, lyrics via Whisper alignment) */\nwindow.MVDATA='+json.dumps(data,ensure_ascii=False,separators=(',',':'))+';\n'
_js = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'js', 'data.js')
open(_js, 'w', encoding='utf-8').write(s)
open('data.js','w',encoding='utf-8').write(s)
print('dur',dur,'N',N,'bytes',len(s))
